### ISSUE TITLE
Can't serialize transaction without fee

### ISSUE THREAD

**Issue by dskloet** [bitpay/bitcore#1094]
Some transactions are perfectly fine to send without fee but in order to allow a transaction without fee I have to disable all safeties, risking a fee of > 1 BTC. Please don't tie the checks for too little fee and too much fee together. 

Also, the error message doesn't make sense:
"Fees are not correctly set Fee is less than 15 times the suggested amount"

Of course it's less than 15 times the suggested amount. Why would I pay 15 or more times the suggested amount? Also some punctuation seems to be missing.

**Comment by maraoz** [comment]
ACK. we'll review this. Thanks for reporting!

**Comment by eordano** [comment]
Hi @dskloet ! Thanks for the feedback. I wrote https://github.com/bitpay/bitcore/pull/1107 to address this: I feel that the error message had a syntax error (it should have been "Fee is 15 times less than the suggested amount"). Changed also the name of the internal check to `_getFeeError`; so in case you know your outputs are too old and you don't need to send a fee, you can just `uncheckedSerialize` and run the `_hasDustOutputs` check.

This still doesn't fix this completely, because I couldn't come up with a nice interface to do so. What do you think about a boolean method named `.isFeeTooLarge()`? I feel weird also because it's very tied to the rigid fees and the recently released 0.10 has this feature called "floating fees" that makes it imposible to calculate the cheapest fee you can pay without being connected to the network, listening to transactions and watching what transactions are getting included in blocks.

**Comment by dskloet** [comment]
I don't like having to disable all checks and then manually doing the checks I want. It means that if you add one more safety check I don't get it without explicitly calling it as well. How about doing all checks by default and allowing individual checks to be disabled? So I could do
```
tx.serialize({disableMinFeeCheck: true})
```
and I would still get every other check. Even checks added in the future.

**Comment by maraoz** [comment]
@dskloet I like that approach too

**Comment by eordano** [comment]
https://github.com/bitpay/bitcore/pull/1109/files

**Comment by maraoz** [comment]
@dskloet I'll close this, I think https://github.com/bitpay/bitcore/pull/1109/ solves all your concerns.

**Comment by dskloet** [comment]
Yes, thanks for the quick fix!

**Comment by pagalsurd** [comment]
This issue is still occuring in bitcore playground. Please update there.

**Comment by maraoz** [comment]
Thanks for the heads up, I'll check that!
