### ISSUE TITLE
BSD support for Bitcore

### ISSUE THREAD

**Issue by anduck** [bitpay/bitcore#1374]
Apparently bitcore doesn't run on (Free)BSD. Will there be support for BSD?

**Comment by kleetus** [comment]
I am curious if you have tried compiling Bitcore for FreeBSD? This can be done by:

using Node.js version 4.2.3

$ npm install bitcore

The project should build from source because binaries won't be found. So as long as have the various compilers toolchains (autotools, etc.) you should be able to make this happen. 

One caveat is the build scripts may fall through to assuming linux. Sorry for that. You can run the scripts, see where it breaks and simply massage the scripts to make it work. I haven't used BSD in some years or I could jump in and assist.

**Comment by kleetus** [comment]
should we keep this issue open or close it out? Of course, we would happily take merge requests for BSD support. I love FreeBSD, NetBSD, OpenBSD so this would be very welcome addition.

**Comment by anduck** [comment]
I tried to compile but I didn't make it. It won't start compiling because it detects unsupported platform (npm detects.)

**Comment by braydonf** [comment]
Is that from cloning https://github.com/bitpay/bitcore-node directly, and running `npm install`? Those checks (https://github.com/bitpay/bitcore-node/blob/master/package.json#L80) only apply if it's a dependency from what I understand. Otherwise it could be modified to test the build.

**Comment by anduck** [comment]
Ah, that way it starts compiling but gmake fails soon.

**Comment by braydonf** [comment]
We've moved to building bitcoin directly in the latest release, please let us know if there are still any issues. You may need to build and run bitcoind independently (https://bitcore.io/guides/bitcoin).
