### ISSUE TITLE
Build error on centos 6

### ISSUE THREAD

**Issue by kreshendo** [bitpay/bitcore#1380]
I have been trying to get bitcore to install on my centos 6 server for the past few weeks and I keep getting the same build error. 

I have updated everything on my server that is needed to run bitcore:

node version 4.2.3

gcc version 5.3.0

python 2.7

i keep getting this error and i don't know what to do. I just want to get this node running asap. please someone give me an idea as to why this isnt working. 

make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
make: Leaving directory `/usr/local/lib/node_modules/bitcore/node_modules/leveldown/build'
prebuild ERR! build error 
prebuild ERR! stack Error: `make` failed with exit code: 2
prebuild ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/bitcore/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! stack     at emitTwo (events.js:87:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:172:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok 
prebuild ERR! build Error: `make` failed with exit code: 2
prebuild ERR! build     at ChildProcess.onExit (/usr/local/lib/node_modules/bitcore/node_modules/node-gyp/lib/build.js:276:23)
prebuild ERR! build     at emitTwo (events.js:87:13)
prebuild ERR! build     at ChildProcess.emit (events.js:172:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
/usr/local/lib
└── (empty)

npm ERR! Linux 2.6.32-573.12.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/bin/npm" "install" "-g" "bitcore"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! leveldown@1.4.3 install: `prebuild --download`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the leveldown@1.4.3 install script 'prebuild --download'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs leveldown
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/npm-debug.log
npm ERR! code 1

I have created a bitcore superuser and added it to the sudo users file and everything that I have seen suggested on this issue page https://github.com/bitpay/bitcore/issues/1376 but nothing has worked. Please help my i need this server running by this weekend. Thank you for any help you could offer.

**Comment by braydonf** [comment]
I'm unable to reproduce the issue, I've tested installation with a fresh install of CentOS 7 (after installation of `git`):

```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.0/install.sh | bash
nvm install v4
npm install -g bitcore
```

**Comment by kreshendo** [comment]
my server is running centos 6.7 

At this point I have bitcore installed globally but when I try to create a bitcore node I am getting this error. 

/usr/local/lib/node_modules/bitcore/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/build/Release/bitcoind.node)
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at bindings (/usr/local/lib/node_modules/bitcore/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/lib/services/bitcoind.js:5:35)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by kreshendo** [comment]
I see there is no way to update this library. I think getting  a bitcore node on this server is just a lost cause. My hosting company won't do any upgrades to the OS and the version I'm running is just too old to build bitcore. 

depression.

**Comment by kleetus** [comment]
I'll be happy to help out here if I can. I am sorry that you've been going through some trials (I've been there many times myself). Getting this running no centos 6.7 is definitely possible! He is what I would do: 

1. You will need to build all the C++ code from source (but it isn't that hard I promise). 
 
Some background about how all this works: 

Bitcore is written in a combination of languages, mostly Javascript (targeting Node.js for the bitcoin full node) and C++. Centos 6.7 does not appear to have a recent enough version of GLIBC for the binaries that we provide. We build the binaries against Ubuntu 12.04. Here is the exact output from the "ldd" command from the build machine:

$ ldd ~/bitcore-node/build/Release/bitcoind.node

libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa7357b8000)

turns out that (on my Ubuntu 12.04 box) this libc.so.6 binary is symbolically linked to:

 /lib/x86_64-linux-gnu/libc-2.15.so (symlinking is very typical to support patch upgrades to the c library that don't break the api to the c library)

This is where the error about "GLIBC_2.15" is coming from. GLIBC is libc (at least on Linux).

So this libc.so.6 thing is dynamically linked into the binary that we provide. Your CentOS version is probably symlinked to a slightly older version of libc (glibc). Not to worry, we can fix this.

2. If you can't install a C++ compiler and build tools on your VPS (which is likely), then you can certainly do this on a VM (like in Virtual Box) that matches the same set of shared libraries. I "think" that CentOS 6.x provided glibc-2.12. So you can probably install CentOS 6.7 in a VM and run the rest of the commands that I provide and then secure copy over the binaries to your VPS and you'll be all set.

A source install on CentOS (or any Red Hat-related OS):

1. Refer to this build doc under the Fedora section:
https://github.com/bitpay/bitcore-node/blob/master/docs/build.md

2. Here are the directions enumerated (this is repeat the same info from the aforementioned link)

- install centos 6.7 in a VM (VirtualBox will work nicely)
- run this comand to get dependencies for building from source:

$ sudo yum install libtool automake autoconf pkgconfig openssl make gcc gcc-c++ kernel-devel openssl-devel.x86_64 patch git
$ git config --global user.email "you@example.com"
$ git config --global user.name "Your Name"

- install nvm from here: https://github.com/creationix/nvm#install-script
- once nvm is installed close the terminal and reopen it
- then run the following commands to get the source compiling (compilation takes 15 minutes on a very modern Mac Book Pro, so YMMV)

$ nvm install v4
$ nvm alias default v4
$ nvm install -g bitcore (this should work, but not run after the fact)

- edit the package.json of bitcore-node as such

$ cd ~/.nvm/versions/node/v4.2.4/lib/node_modules/bitcore/node_modules/bitcore-node
$ nano package.json

- change the "version" value to: "dev" so the package.json should have a line changed from:
"version" : "1.0.1" 
to 
"version" : "1.0.1-dev"
- save the file and remain in the ~/.nvm/versions/node/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node
directory
- then start the install

$ npm install

- this will take a lot of time, the build system is compiling Bitcoin core from scratch, all of Bitcoin's dependencies such as boost, openssl, and the bindings file. 

- hopefully this works without incident, if not, post ALL of the output back here (feel free to find and replace sensitive info)

- if there no errors, then you will see all of the node modules being installed and if you really want to prove that everything was good to go: then type:

$ echo $?

- the return integer should be '0'

what now? 

- you then have a build system capable of producing binaries for your VPS's. Secure copy the file as such:

$ scp ~/.nvm/versions/node/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/build/Release/bitcoind.node <user>@<host>:<~/.nvm/versions/node/v0.12.7/lib/node_modules/bitcore/node_modules/bitcore-node/build/Release/>

- this assumes the user is the user that you originally performed the npm install -g bitcore (hopefully not root user!)

- once you have this bitcoind.node file over on your VPS, then you can run bitcore as you did before. It should work fine. I admit freely that I haven't actually performed my steps on CentOS version 6.7, BUT I have done this process many times on RHEL, Fedora, and CentOS 7. I even wrote a Dockerfile to automate the install on CentOS official build on Docker hub. https://hub.docker.com/r/kleetus/bitcore/

Let me know how it goes. I am hoping to help not only you, but Google should index this info for others. Admittedly, Bitcore still needs work helping people compiler from source. Autotools (autoconf, libtool, automake) aimed to be user-friendly, but they are not unless you know a bit about the toolchain.

**Comment by kreshendo** [comment]
Thank so much for helping me out. 
Well I already have all of the tools installed on my vps server so I was able to perform the steps on my machine. "npm install" failed with this error: 

libtoolize: copying file `build-aux/m4/lt~obsolete.m4'
configure.ac:936: error: possibly undefined macro: PKG_CONFIG_LIBDIR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

npm WARN enoent ENOENT: no such file or directory, open '/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/bufferutil/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/node-gyp-install/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/prebuild/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/node_modules/utf-8-validate/package.json'
npm ERR! Linux 2.6.32-573.12.1.el6.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! bitcore-node@1.0.1-dev install: `./bin/install`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the bitcore-node@1.0.1-dev install script './bin/install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs bitcore-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/bitcore/node_modules/bitcore-node/npm-debug.log

**Comment by braydonf** [comment]
I would try git cloning the [bitcore-node](https://github.com/bitpay/bitcore-node) repository directly and checkout the v1.0.1 release to build: https://github.com/bitpay/bitcore-node/tree/v1.0.1 There may be issues while building as a dependency (just spawned https://github.com/bitpay/bitcore-node/issues/390 to verify this fact).

Also just spawned an issue to have an better option to build from source: https://github.com/bitpay/bitcore-node/issues/389 (instead of needing to modify the version string) I think this case has come up a few times and could be useful.

**Comment by braydonf** [comment]
Original looks to be because `sudo` or *root privileges* when installing, same as: https://github.com/bitpay/bitcore-node/issues/426
