### ISSUE TITLE
Litecoin implementation 

### ISSUE THREAD

**Issue by number7team** [bitpay/bitcore#1387]
Has anybody tried to get bitcore working with litecoin or any other fork? Is it possible?

**Comment by kleetus** [comment]
in fact, we have. It is not public though, work in progress. It is definitely possible

**Comment by bityogi** [comment]
bitcoinjs-lib already does have integration. You could possibly simulate that behavior by looking at what they are doing.

**Comment by braydonf** [comment]
You can add any custom network with: https://github.com/bitpay/bitcore-lib/blob/master/lib/networks.js#L67

**Comment by braydonf** [comment]
It also may be possible to compile against different forks by modifying https://github.com/bitpay/bitcore-node/blob/master/bin/build#L140 so long as this patch can apply https://github.com/bitpay/bitcore-node/blob/master/etc/bitcoin.patch

**Comment by rjmacarthy** [comment]
I'd be interested in this too.

**Comment by manuel-di-iorio** [comment]
+1

**Comment by hideoussquid** [comment]
The issue is twofold: I got the insight-api/ui working by downloading the bitcore fork of the bitcoind and recompiling that with the necessary adjustments for my particular alt coin. Most alts will not have the necessary indexing that bitcore added. If you can port those indexes into your alt and just use that, it may work.
Next, you have to go into networks.js and add a network with prefixes/magic numbers that match.
Since I was doing it quick & dirty I just replaced the values in the livenet entry. It seems to work fine.
Now, getting BWS/Copay to work with it is another story altogether...

**Comment by losh11** [comment]
If anyone is still wondering, Bitcore has been ported to support Litecoin.

Litecore is available at: https://github.com/litecoin-project/litecore

**Comment by lp12ucw** [comment]
Can any body help me please Yano I’m bit vip the lot iv got 2 fecking master keys ffs bust I still don’t know how to deposit a damm bic 🙈 it’s embarrassing 🤣 I duno if it’s coz I carnt verify my I.d or what pleaseeee I’ll gladly return the favour 😉
