### ISSUE TITLE
Distributing-Only Wallets roadmap?

### ISSUE THREAD

**Issue by igorvlassov** [bitpay/bitcore#1402]
Dear Sirs,
Is there some recomendations/roarmap for most secure bitcoins acceptance on web server using bitcore stack? Like Distributing-Only Wallets. 
Thanks,
Igor

**Comment by dabura667** [comment]
Please clarify.

**Comment by igorvlassov** [comment]
https://bitcoin.org/en/developer-guide#distributing-only-wallets

**Comment by dabura667** [comment]
I don't think there is a pre-made service that does that using bitcore, but there's mycelium gear:

https://github.com/MyceliumGear/straight-server

This is only if you want to run it on your own server.

You can sign up for free using Mycelium's server:

https://gear.mycelium.com/

Since all you give them is the master public key, they can not control your funds.
