### ISSUE TITLE
Bitcore node returning only 10 Transaction

### ISSUE THREAD

**Issue by PeterRogers123** [bitpay/bitcore#2194]
When running the Bitcore node and Requesting transaction by address it only returns 10 results where as the address has almost 400 transaction in its history.

How can we get all transactions instead of just the last 10.

This is when using method request below:
http://localhost:3000/api/BTC/testnet/Address/address/txs

I know the address : n4VQ5YdHf7hLQ2gWQYYrcxoE5B7nWuDFNF 
This has over 500 Transactions.

Please assist me if you have somehow solved this issue.

**Comment by micahriggan** [comment]
https://github.com/bitpay/bitcore/blob/master/packages/bitcore-node/src/routes/api/address.ts

The route takes in limit, and since as query params

So you could page through them like:

http://localhost:3000/api/BTC/testnet/Address/address/txs?limit=100&since=ObjectId

Then you get the next page by setting `since` to the last _id you got from the previous response

**Comment by PeterRogers123** [comment]
Thank you that worked perfectly i actually figured this out yesterday i just hadnt been online again yet since!
