### ISSUE TITLE
Message magic hash

### ISSUE THREAD

**Issue by Raylin51** [bitpay/bitcore#3655]
Why is the string definition of `Message.MAGIC_BYTES` set as `'Bitcoin Signed Message:\n'` instead of `'\u0018Bitcoin Signed Message:\n'`?

**Comment by kajoseph** [comment]
This mirrors the Bitcoin Core implementation and otherwise follows standard practices for message signing to include the len(MAGIC_BYTES) + MAGIC_BYTES + len(msg) + msg. This is implemented in `Message.prototype.magicHash`.

The static length of 18 is, as far as I can tell, most likely from the [BitID spec](https://github.com/bitid/bitid#wallet-implementation-requirements) which deviates from standard bitcoin message signing.
