### ISSUE TITLE
check that we're not including bitcore twice for browser apps using a submodule

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore#901]

**Comment by braydonf** [comment]
This should be noted in the writing a module guide, as something to watch, as with browserify it's quite easy to include by mistake without the correct parameters.

**Comment by eordano** [comment]
Have some feedback about this from working on streamium. It turns out that `browserify --external bitcore` is not compatible with `require('bitcore/lib/...');` (the path in the require makes it hard for browserify to detect that `bitcore/lib/...` is the same dependency as `bitcore`). So, there are two ways to address this: either add to the browserify command all the required modules (which is possibly a maintenance nightmare), or drop the "library subpath require pattern".

**Comment by braydonf** [comment]
Fixed with commit: https://github.com/bitpay/gulp-bitcore/commit/7c30479052c7772ca173b4a31377a98eacd865aa

By using these browserify commands instead of using `--standalone`:
```bash
browserify --require index.js:bitcore -o bitcore.js
browserify --require index.js:bitcore-ecies  --external bitcore -o bitcore-ecies.js
```
