### ISSUE TITLE
Idea: Remove network from all objects

### ISSUE THREAD

**Issue by yemel** [bitpay/bitcore#919]
Most bitcoin applications *do not handle livenet and testnet network at the same time*. There are just a few use cases that needs to work on both, eg. Copay supports wallets in both `livenet` and `testnet` simultaneously.

For the first and most common scenario, we created the `Networks.defaultNetwork` global variable. This goes along the philosophy of _"write your application once, run it everywhere"_.

However for the second scenario, we decided to keep the `network` parameter on every interface. I believe this is the wrong way to go, here are some cons I see:

* It clutters the API, on both constructors and methods.
* It clutters the documentation, network parameters are in every example.
* All immutable objects have a twin brother on the other network, which is awkward.
* Some objects are network-aware and others aren't, which is confusing.
* There is no clear consensus about what should be network-aware (eg. Public Key class).
* Having no network-aware objects creates consistency problems for example:

```
var address = new Address('myvL5d7Bnx6XCS1D2UzwW9Bf9RckC32zKm');
var script = new Script(address);
address.toAddress() // returns a livenet addres!
```
Actually this is false, because we make [a hack](https://github.com/bitpay/bitcore/pull/888) to avoid it.

Other huge problem of the current approach is that our test coverage is a lie. We should be testing our code in all posible scenarios: using the defaultNetwork, explicitly using livenet and explicitly using livenet. Later we should run the test suite twice, changing the defaultNetwork value. I'm sure we are not covering all branches. And this is because the network parameter is a hazzle.

My proposal is to remove every network from the parameters and object state. When a network is needed the `Network` context variable (aka `defaultNetwork`) will be used. If you need to manage both `livenet` and `testnet` on your application, you could instantiate bitcore with a new network context.

Using a context variable, write it once and run it everywhere:
```
var network = process.env.NETWORK;
var bitcore = require('bitcore').use(network);

var address = new bitcore.PrivateKey().toAddress();
```

Managing different networks:
```
var bitcore = require('bitcore');
var bitcoreLive = bitcore.use('livenet');
var bitcoreTest = bitcore.use('testnet');

var addressLive = new bitcoreLive.PrivateKey().toAddress();
var addressTest = new bitcoreTest.PrivateKey().toAddress();
```

--- Updated 28/01
Or something like this
```
var bitcoreLive = require('bitcore')('livenet');
var bitcoreTest = require('bitcore')('testnet');

var addressLive = new bitcoreLive.PrivateKey().toAddress();
var addressTest = new bitcoreTest.PrivateKey().toAddress();
```

**Comment by braydonf** [comment]
The network is a part of the encoding of an HDKey as well as a private key, there are other such scenarios. I'd lean more towards not having a defaultNetwork parameter, or making it non-configurable, and to not depend on global state that can cause problems.

There was a very confusing bug that was caused by depending on the global state of defaultNetwork in HDPublicKey, where an error that was supposed to happen didn't because it wasn't properly detecting the extended private key encoding. Here is the fix: https://github.com/bitpay/bitcore/commit/8b505f0cfa93bbbbaa1beb230b540036c960e561#diff-2f4a47328971231baa9494b48e580b6bL197 However finding the cause was fairly complex because of the code paths that alter based on the type of data, and errors produced, or in the case above the lack of an error.

**Comment by braydonf** [comment]
Considering that address, private keys and extended private keys have the network property as part of the serialization, network needs to a property of these instances.
