### ISSUE TITLE
Evaluate caching techniques used through bitcore

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore#950]
There are a few cache patterns that we are using:

* There's an effort to avoid reinstantiation of instances that are immutable: for example, Addresses and all the *Key instances (Public, Private, HDPublic, HDPrivate) will test the parameter to the constructor object and it will not instantiate a new object.
* There's the HDKeyCache class that provides a cache of instances
* The Input and Output instances store a copy of the script as buffer
* The output instances store both _satoshis (a number), and _satoshisBN (a big number) to avoid reconverting to/from bignumber

These should be carefully reviewed and removed if they can introduce frailty

**Comment by braydonf** [comment]
For the last two on the list:
- The output `._scriptBuffer` is necessary since scripts can be invalid, and an instance of Script can not be instantiated, however the data needs to still be on the object.
- For the output satoshis, the `_satoshis` (number) can not fully represent 64bits accurately, however for bitcoin the max number of satoshis is 21000000 * 1e8 (less than 2 ^ 53 - 1), and can safely be represented as a number. However serialization still needs to support the larger numbers. Having `_satoshisBuffer` read during parsing (and support the full range of numbers), and lazy read into a number, would help with performance.
